### ISSUE TITLE
[add][database][IRONdb] 

### ISSUE THREAD

**Issue by kamelkev** [xephonhq/awesome-time-series-database#50]
## Type of action

- add

## Content

- https://www.circonus.com/irondb/

## Category

Databases

**Comment by at15** [comment]
@kamelkev Thanks! I did opened one for iron db https://github.com/xephonhq/awesome-time-series-database/issues/40, but there are just too many issues (opened by myself). I will spend sometime to clean them up this weekend

**Comment by kamelkev** [comment]
Apologies. I should have done a better job of looking through. Thanks.

**Comment by at15** [comment]
Well ... my weekend took almost 2 years ... you find irondb at https://xephonhq.github.io/awesome-time-series-database/database/irondb.html
