### ISSUE TITLE
[add][database][VictoriaMetrics]

### ISSUE THREAD

**Issue by at15** [xephonhq/awesome-time-series-database#63]
## Type of action

- add

## Content

- https://github.com/VictoriaMetrics
- [ ] it seems the db repo is still close source ... (based on author's contribution history on github ...
-  https://github.com/VictoriaMetrics/fastcache in mem cache (use bucket to shard and reduce gc? seems to be the trick for all of its kind ... didn't compare w/ sync.Map?)
- https://medium.com/devopslinks/victoriametrics-creating-the-best-remote-storage-for-prometheus-5d92d66787ac

## Category

Database

## Reason (Optional)

- inspired by click house but roll their own due lack of support on label (index meta data)
- yet another tsdb written in go

**Comment by valyala** [comment]
VictoriaMetrics is open-source now - see https://github.com/VictoriaMetrics/VictoriaMetrics
